image: nixos/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- nixos.hut
- nixos.pandoc
tasks:
- build: |
    mkdir build/
    cd add512.me/

    ./Main.hs 4>feed.xml *.md > index.md

    for f in *.md;
      do pandoc -H head.html "$f" -o ~/build/"${f%.*}".html;
    done
    cp feed.xml ~/build/
- package: |
    cd ~/build/
    tar -cvz . > ~/site.tar.gz
- upload: |
    hut pages publish -d add512.srht.site site.tar.gz
